server:
 port: 8888

spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/skybeast_db
  username: postgres
  password: postgres
 jpa: 
  hibernate:
   ddl-auto: update
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect